### ISSUE TITLE
ASI issues

### ISSUE THREAD

**Issue by adrianheine** [marijnh/blint#2]
blint thinks there should be semicolons in these cases:

```
  if (widget.noHScroll) {
    (lineView.alignable || (lineView.alignable = [])).push(node)
  }
```

```
  if (m.endStyle && sp.to == nextChange) (endStyles || (endStyles = [])).push(m.endStyle, sp.to)
```

blint doesn't think there should be a semicolon in this case:

```
      off -= sz
      ++lineNo
```

**Comment by marijnh** [comment]
I considered turning that off for single-statement blocks/bodies, but that felt a bit too much like courting disaster. Thinking about it a bit more, there's probably no realistic failure scenario (if you ever refactor the code to make it a multi-line body, the linter will yell at you at _that_ point).

I'll change that.

Is there an issue with the last example? `++` isn't parsed as a postfix op when a semicolon can be inserted before it, so that code will mean what it looks like.

**Comment by adrianheine** [comment]
You're right about the latter. ESLint doesn't automatically remove it, so I thought it might get parsed as `off -= sz + +lineNo` or something like that, but gladly that's not the case and ESLint agrees with you accepting it without any semicolon.

**Comment by adrianheine** [comment]
Another one:

```
if (i == 0) {
} else {
  (lineView.measure.maps || (lineView.measure.maps = [])).push(builder.map)
}
```

And:

```
if (widget.noHScroll) {
  (lineView.alignable || (lineView.alignable = [])).push(node)
}
```

**Comment by marijnh** [comment]
I don't think I want to make exceptions for the first statement in a block. The semicolon-free-safety rules are already somewhat complicated, and I think putting a semicolon before every potentially-unsafe line is a decent rule of thumb.
